### PR TITLE
PNDA-2832: Jupyter %sql magic support.

### PR DESCRIPTION
**Pull request by GaneshManal**
# Problem Statement:
PNDA-2832: Jupyter %sql magic support.

# Analysis:
The Jupyter notebook should be able to support the sql-magic extension along with other extensions.

# Change:
pnda - Added the sql-magic extension support related packages to the mirror repository.
platform-salt - Install the sql-magic extension support related packges to the kernel supporting virtual environments.

# Test details:
Verified the fix for AWS:
UBUNTU - PICO -CDH & HDP
UBUNTU - STD  -CDH & HDP
RHEL   - PICO -CDH & HDP
RHEL   - STD  -CDH & HDP
Verification pending for OpenStack

### CODE REVIEW

**Comment by willis27** [comment]
What is the different of %sql between magic spark and ipython-sql? if both are installed, potential conflicts, for example, a notebook that uses sparkmagic python kernel may also load ipython-sql extension?

**Comment by GaneshManal** [comment]
# sqlmagic - 
Connect to a database, using SQLAlchemy connect strings, then issue SQL commands within IPython or IPython Notebook.
sqlmagic is loaded using {load_ext sql},  once available we got to connect to database using connect string and then we can query. 

# sparkmagic - 
Sparkmagic is a set of tools for interactively working with remote Spark clusters.
kernel with sparkmagic support, loads the sparkcontext & hivecontext obejects and cell can work with spark using sql magic (%sql).  

# Now lets consider the potential conflict case for our current setup -
We have python pyspark Kernal, if it has sparkmagic support, then there are 2 ways to get the sql magic -

1.  loading sql magic - %load_ext sql
2.  implicitly received from spark-magic i.e. spark context object ( initialized when kernel notebook started).

until we do not load the sql-magic, there wouldn't be conflict and sql magic will interact with remote spark.
once we load sql-magic, by providing connect string, we have multiple sql connections.

In this case, we have to provide the connection string for the open connection in order to query.
if no connection string is provided, it gives the list of available connections.
I suppose, the %sql magic usage here will provide list of connections along with the one available for spark context.
And by providing the connection string we will be able to connect.
Reference - https://github.com/catherinedevlin/ipython-sql
https://github.com/jupyter-incubator/sparkmagic

__This is based on theory, I will re-validate the case practically and will update.__

**Comment by willis27** [comment]
Does ipython-sql support Hive connection? It seems it only supports msyql/posgresql. If this is the case, maybe SparkMagic %sql is good enough. Agree?

**Comment by willis27** [comment]
dependencies of MYSQLDB and Psycopg2 are missing. Should they be supported by default for the use of ipython-sql magic?

**Comment by GaneshManal** [comment]
ipyton-sql doesn't support Hive connection unless it has spark-context available.
I feel,spark-magic is not good enough considering we have to provide sql magic support for **non-spark-kernel notebooks**.

**Comment by GaneshManal** [comment]
Default support for database connection like **MYSQLDB** & **Psycopg2** -
While verifying the functionality we verified sql magic is available, And didn't really tried to make explicit connection to the database.
We can consider to provide them as  an enhancement, or adding them to current enhancement if you recommend.

**Comment by willis27** [comment]
Default driver supports requirements need to be added in the provisioning. In particular:
CDH: MYSQLDB, Psycopg2, Impala (https://github.com/cloudera/impyla)
HDP: MYSQLDB, Psycopg2

**Comment by GaneshManal** [comment]
Above specified default driver support is added.

**Comment by willis27** [comment]
Fix requests:
a) Please try to follow a consistent format as other example notebooks do - i.e. having a title cell.
b) a typo: %sql mysql+pymysql://usernamer:password@hostname/dbname - username instead of usernamer?

**Pull request merged**
