### PR TITLE
PNDA-1322: Test Master Dataset Health

### PR DESCRIPTION
**Pull request by Manasa-Sriram-ML**
# Problem Statement:
PNDA 1322: Test Master Dataset Health

# Analysis:
Check initial creation of dataset to track GOBBLIN Health.
Test Master Dataset Health by keeping track of HDFS directories/files created by GOBBLIN.

# Changes:
Modified gobblin Job configuration file(mr.pull) in salt. Kafka Test topic(avro.internal.testbot) has been removed from blacklist to test Master Dataset Health.
Modified Platform-testing in salt. Added two more inputs(data-service-ip and cluster-name) to KAFKA service to test dataset creation and it's health. 
Also modified KAFKA service and conf templates inside platform-testing templates directory to create a service file with new inputs.
Modified PNDA.py module to get data-service IP by giving it's role.
Added new GOBBLIN Job configuration file to test initial creation of dataset to track GOBBLIN Health. This Job configuration file will allow data only from TEST Topic(avro.internal.testbot)
To run with new Job configuraion, added service and conf templates in templates directory. 
Added a new step in gobblin init.sls state file to install these new service scripts.

# Test details:

Verified changes in AWS environment(OFFLINE/ONLINE):

UBUNTU-PICO-CDH
UBUNTU-STD-CDH
UBUNTU-PICO-HDP
UBUNTU-STD-HDP
RHEL-PICO-CDH
RHEL-STD-CDH
RHEL-PICO-HDP
RHEL-STD-HDP

### CODE REVIEW

**Comment by trsmith2** [comment]
This appears to be creating a new Gobblin process that runs alongside the existing one. We need to test the existing process.

**Comment by MANASASRIRAMENENI** [comment]
New Gobblin process is created to test Gobblin health initially that is immediately after deployment. It doesn't run as a CRON Job, it just runs initially once to check the creation of dataset and report the health metric as gobblin_health.

Existing Gobblin process runs as a CRON job every 30 minutes continously..

**Comment by trsmith2** [comment]
Why not just run the existing Gobblin process?

**Comment by MANASASRIRAMENENI** [comment]
Existing Gobblin process allows data from all KAFKA Topics whereas the newly created Gobblin process allows data only from the test topic 'avro.internal.testbot' by adding a new parameter "topic.whitelist" in "mr.pull.test". This is the only reason because of which I created a new Gobblin service to run new Job configuration file which has the above configuration change..

**Comment by trsmith2** [comment]
We've discussed this a little and we think -
- We should be testing the existing Gobblin process, not creating a new one
- The test data put on to Kafka should include good & bad examples (upgrade to Kafka test)
- The Kafka test should otherwise continue to focus on testing Kafka
- The Datasets test should be a separate test and checking the good/bad data on HDFS

There's an design consideration here around synchronicity - the Kafka test doesn't need to concern itself with Gobblin, but the Datasets test should make sure not only that good/bad data is correctly captured, but also that it is regularly captured.

There's an edge case to consider regarding what happens when the cluster is first created. We would suggest to think about triggering the first run of Gobblin soon after the first Kafka test runs, and to think about a simple eventing or sentinel mechanism to demarcate the 'Gobblin has never been run' state so that the Datasets test can behave appropriately.
 
I've raised these comments on platform-salt but they're obviously application to the corresponding PR on platform-testing as well (https://github.com/pndaproject/platform-testing/issues/44)

**Comment by trsmith2** [comment]
Closing until further update on this

**Pull request closed without merging**
