### PR TITLE
PNDA-1899: Scala Spark Jupyter Integration

### PR DESCRIPTION
**Pull request by mrunmayeejog**
# Problem Statement:
PNDA-1899: Scala Spark Jupyter Integration

# Analysis:
Scala support for Spark coding is provided by adding two new kernels along with other kernels in Jupyter notebook - 
1. Scala kernel is added for standalone Scala programming.
2. Spark kernel is added by installing Sparkmagic and Apache livy. Sparkmagic facilitates interaction with remote Spark cluster through Livy. Apache livy is a RESTful service that enables this interation with remote Spark cluster.

# Changes:
1. For adding Scala kernel, scala kernel package is installed and configured. Kernel template for scala is updated and added to jupyter's kernel directory.  
2. For adding Spark kernel, sparkmagic and livy server are installed and configured. Spark kernel template is updated and added to jupyter's kernel directory. Livy is provided as a service which preserves its state on system reboot.
3. For both the newly added kernels, sample notebooks are provided for verification.

### CODE REVIEW

**Comment by trsmith2** [comment]
Some questions/comment on the code -
- Could you briefly explain why Kerberos needs to be introduced?
- Please don't use hard coded paths for directory locations
- The library being used here is a SNAPSHOT, which implies volatility. Is this the right version?
- Please supply URL to source of salt/jupyter/templates/jupyter_scala_exe.tpl
- Missing newline at EOF of salt/jupyter/templates/scala_spark_kernel.json.tpl

**Comment by mrunmayeejog** [comment]
Please find comments:
1. As per the requirement specifications of sparkmagic, its dependencies include request_kerberos which internally required pykerberos. Hence pykerberos and its required package dependencies were introduced.
2. Can you specific one for example.
3. Currently other builds for jupyter-scala are available and they worked for online deployment mode. However we faced issues in case of offline mode. The build uses coursier which is a package dependency resolver which looks for packages in online repos. We tried configuring it for offline mode but dependencies increased. Hence used current SNAPSHOT mirror which provides all the required dependencies.
4. Will look into it and get back.
5. Will modify this.

**Comment by trsmith2** [comment]
_Can you specific one for example_

The virtualenv location for library installation is one example

**Comment by mrunmayeejog** [comment]
Closing PR for PNDA-1899 as working on required modifcations. Will raise new PR post testing.

**Pull request closed without merging**
