### PR TITLE
PNDA-4606: Append domain name if "search" string doesn't exist

### PR DESCRIPTION
**Pull request by Manasa-Sriram-ML**
Replacing domain name if search string already exists and appending domain name if search string doesn't exist (In /etc/resolv.conf)

### CODE REVIEW

**Comment by trsmith2** [comment]
Can you have a look at SaltStack's file.line and see if that does what you need. You shouldn't need the cmd.run and conditional here.

**Comment by Manasa-Sriram-ML** [comment]
Trevor,

Had to include a condition to check if "search" string already exists or not because if "search" string doesn't exist in the file it's appending the whole content along with "**\1**" in resolv.conf('search {{ domain_name }} \1')
Using file.replace with "append_if_not_found: True" flag to make sure it adds domain name if search doesn't exist

Tried using file.line but the problem with it is, it is trying to add or replace content in a new line(if we use after or before Flags to match a keyword)
Ex:/etc/resolv.conf(If search already exists)
search
{{ domain_name }}

**Comment by trsmith2** [comment]
The problem is that apart from looking a little strange, this won't actually work. Every time you run it, it's going to grow the search statement, prepending an entry each time. States should be idempotent.  

You can reproduce what you have at the moment with one command - file.replace, with a simpler regex (just look for 'search') and use append_if_not_found (which will work fine as you don't need the /1). That will have the same bug of growing the search statement forever.

What you actually want is to add the desired domain only if it doesn't already exist in any position on a search statement, or add a search statement if there isn't already one present. You might be able to do that with a better regex (look at negative look-ahead and so on). Otherwise, you might be outside what you can really do declaratively, and need to use a short script. 

Finally, if you're able to supply the local domain you expect to be present then you could simply write the correct resolv.conf in the first place.  This ought to be known at deployment time.

**Comment by Manasa-Sriram-ML** [comment]
Trevor,

Updated dns.sls in such a way it handles three cases:
1. Grep for "Domain Name" in particular if it is present in any position of the "search" line and exit without performing any action if succeeds
2. Grep for "search" if 1st condition doesn't satisfy and replace search line with domain name in 1st order
3. Appends "search domain_name" if above conditions doesn't satisfy

This will make sure by adding domain_name only if it doesn't exist in the file. And also just wanted to mention there is already a state in dns.sls to modify permissions of resolv.conf so that it can never be modified once executed(When we run consul state again it doesn't allow to add domain name second time)

**Comment by trsmith2** [comment]
I think this is better, but I'm still concerned about robustness. Do these regexes need anchoring? For example what happens if I deploy in a company using a domain called yellow*search*light.org? 

To the last point, while file permissions may save this from going wrong in that respect, it would be better not to rely upon it. The logic required here is actually quite simple, the complexity is only arising from trying to do this declaratively and again, I do wonder whether it might be clearer and more maintainable to just separate it out.

Let's address the regex question first.

**Comment by Manasa-Sriram-ML** [comment]
Trevor,

Made few changes to regex expression to handle corner cases that have been mentioned:

1. Modified first "if" condition to grep only if "search domain_name" exists on a new line with a "space" and also using "-w" to grep search only if it's a word but not as string(yellowsearch.com). 
2. Modified second condition to grep if "search" starts on a new line along with space and using "-w" to grep if it is a word but not string
3. Modified third condition to "ignore_whitespace" because if there is a case where resolv.conf has "search<domain_name>"(No space between search and domain_name), it doesn't append a new line because by default it ignores white space

Cases Handled:
1. nameserver yellowsearchlight.com
 >> Result: Adds a new line search <domain_name>
2. search   yellowsearchlight.com
  >> Result: search <domain_name> yellowsearchlight.com
3. #search localsearch
  >> Result: Adds a new line search <domain_name>
4.     search <domain_name> (space in beginning)
     >> Adds a new line search <domain_name>
5. searchlocaldomain (No space between)
  >> Result: Adds a new line search <domain_name>

**Pull request merged**
